{"start": 1683043005957, "befores": [{"status": "broken", "start": 1683043005957, "stop": 1683043046863, "name": "ws_client", "statusDetails": {"message": "HTTPError: 401 Client Error: Unauthorized for url: https://oauth.test.ws.sonos.com/auth/oauth/v2/token\n", "trace": "  File \"/test/python/.venv/local/lib/python2.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/test/python/.venv/local/lib/python2.7/site-packages/_pytest/fixtures.py\", line 969, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/test/python/.venv/local/lib/python2.7/site-packages/_pytest/fixtures.py\", line 828, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/test/python/tests/src/pytest_automation/plugins/muse_plugin.py\", line 313, in ws_client\n    return websocket_manager.make_connection(dut_manager.zp)\n  File \"/test/python/.venv/local/lib/python2.7/site-packages/sonos/museclient/websocket_manager.py\", line 41, in make_connection\n    ws_conn = MuseWebsocketClient(ip=zp.ip, secure=secure, apiKey=apiKey, subprotocols=subprotocols)\n  File \"/test/python/.venv/local/lib/python2.7/site-packages/sonos/museclient/muse_websocket_client.py\", line 13, in __init__\n    subprotocols=subprotocols, fetchToken=fetchToken, secureRegCheck=secureRegCheck)\n  File \"/test/python/.venv/local/lib/python2.7/site-packages/sonos/museclient/base_muse_websocket.py\", line 92, in __init__\n    secureRegCheck=secureRegCheck)\n  File \"/test/python/.venv/local/lib/python2.7/site-packages/sonos/museclient/base_muse_rest.py\", line 82, in __init__\n    self.updateOauthTokens()\n  File \"/test/python/.venv/local/lib/python2.7/site-packages/sonos/museclient/base_muse_rest.py\", line 387, in updateOauthTokens\n    tokenObj = OAuth.get_oauth_token(scope=scopeString, username=username, password=password, use_v4=useV4)\n  File \"<decorator-gen-2>\", line 2, in get_oauth_token\n  File \"/test/python/.venv/local/lib/python2.7/site-packages/retry/api.py\", line 74, in retry_decorator\n    logger)\n  File \"/test/python/.venv/local/lib/python2.7/site-packages/retry/api.py\", line 33, in __retry_internal\n    return f()\n  File \"/test/python/.venv/local/lib/python2.7/site-packages/sonos/oauth/common.py\", line 219, in get_oauth_token\n    res.raise_for_status()\n  File \"/test/python/.venv/local/lib/python2.7/site-packages/requests/models.py\", line 960, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"}}], "stop": 1683043047376, "uuid": "ade2cc73-adad-4130-853e-d3b66992d6fc", "children": ["240f991f-5633-4d41-a217-4d4cb41eb863"]}