{"status": "broken", "description": "\n    Automated test for SWPBL-198251: Change Upnp telemetry to report every 10 minutes\n    1. Make sure upnpEventHealth is not reported on subscribe/renew/unsubscribe\n    2. Verify that upnpEventHealth is reported on hitting the testpoint and forcing event upload\n    #curl --data \"{}\" \"http://<ip_addr>:1400/testpoint?name=upnptelemetry\"\n\n    :param module_dut:\n    :param ws_client:\n    :param mock_cq_server:\n    :return:\n    ", "labels": [{"name": "tag", "value": "nightly"}, {"name": "tag", "value": "priority3"}, {"name": "tag", "value": "metric_logging"}, {"name": "parentSuite", "value": "player.muse"}, {"name": "suite", "value": "test_muse_metric_logging"}, {"name": "host", "value": "0957d6a9cfb8"}, {"name": "thread", "value": "1-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "player.muse.test_muse_metric_logging"}], "stop": 1683042975423, "uuid": "240f991f-5633-4d41-a217-4d4cb41eb863", "historyId": "031f4115fe037b9cc52ceb3a16773d8f", "name": "test_upnpeventhealth_no_flooding", "start": 1683042975423, "fullName": "player.muse.test_muse_metric_logging#test_upnpeventhealth_no_flooding", "statusDetails": {"message": "HTTPError: 401 Client Error: Unauthorized for url: https://oauth.test.ws.sonos.com/auth/oauth/v2/token", "trace": ">       lambda: ihook(item=item, **kwds),\n        when=when,\n    )\n\n../../../.venv/local/lib/python2.7/site-packages/flaky/flaky_pytest_plugin.py:306: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nplugins/muse_plugin.py:313: in ws_client\n    return websocket_manager.make_connection(dut_manager.zp)\n../../../.venv/local/lib/python2.7/site-packages/sonos/museclient/websocket_manager.py:41: in make_connection\n    ws_conn = MuseWebsocketClient(ip=zp.ip, secure=secure, apiKey=apiKey, subprotocols=subprotocols)\n../../../.venv/local/lib/python2.7/site-packages/sonos/museclient/muse_websocket_client.py:13: in __init__\n    subprotocols=subprotocols, fetchToken=fetchToken, secureRegCheck=secureRegCheck)\n../../../.venv/local/lib/python2.7/site-packages/sonos/museclient/base_muse_websocket.py:92: in __init__\n    secureRegCheck=secureRegCheck)\n../../../.venv/local/lib/python2.7/site-packages/sonos/museclient/base_muse_rest.py:82: in __init__\n    self.updateOauthTokens()\n../../../.venv/local/lib/python2.7/site-packages/sonos/museclient/base_muse_rest.py:387: in updateOauthTokens\n    tokenObj = OAuth.get_oauth_token(scope=scopeString, username=username, password=password, use_v4=useV4)\n../../../.venv/local/lib/python2.7/site-packages/retry/api.py:74: in retry_decorator\n    logger)\n../../../.venv/local/lib/python2.7/site-packages/retry/api.py:33: in __retry_internal\n    return f()\n../../../.venv/local/lib/python2.7/site-packages/sonos/oauth/common.py:219: in get_oauth_token\n    res.raise_for_status()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <Response [401]>\n\n    def raise_for_status(self):\n        \"\"\"Raises :class:`HTTPError`, if one occurred.\"\"\"\n    \n        http_error_msg = ''\n        if isinstance(self.reason, bytes):\n            # We attempt to decode utf-8 first because some servers\n            # choose to localize their reason strings. If the string\n            # isn't utf-8, we fall back to iso-8859-1 for all other\n            # encodings. (See PR #3538)\n            try:\n                reason = self.reason.decode('utf-8')\n            except UnicodeDecodeError:\n                reason = self.reason.decode('iso-8859-1')\n        else:\n            reason = self.reason\n    \n        if 400 <= self.status_code < 500:\n            http_error_msg = u'%s Client Error: %s for url: %s' % (self.status_code, reason, self.url)\n    \n        elif 500 <= self.status_code < 600:\n            http_error_msg = u'%s Server Error: %s for url: %s' % (self.status_code, reason, self.url)\n    \n        if http_error_msg:\n>           raise HTTPError(http_error_msg, response=self)\nE           HTTPError: 401 Client Error: Unauthorized for url: https://oauth.test.ws.sonos.com/auth/oauth/v2/token\n\n../../../.venv/local/lib/python2.7/site-packages/requests/models.py:960: HTTPError"}, "attachments": [{"source": "8170e9be-483c-4c9b-855d-8ab195a6c73d-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "eacb9e41-9b91-4362-8333-90af04b68d26-attachment.txt", "type": "text/plain", "name": "stderr"}]}